<?php

namespace AppBundle\Repository;

/**
 * AttendenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendenceRepository extends \Doctrine\ORM\EntityRepository
{
}
