imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    default_locale: 'en'
    translator:
      { fallbacks: ["en"] }
    templating:
        engines: ['twig']

    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
#    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
#        cookie_lifetime: 10
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

# config/packages/easy_admin.yaml
easy_admin:

    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
#    - { label: 'User', role: ROLE_ADMIN } # Hidden if user is not granted ROLE_SUPER_ADMIN
#    - { label: 'User', route: '/easyadmin', role: ROLE_ADMIN } # Hidden if user is not granted ROLE_ADMIN
    design:
#        form_theme:menu:
#                - { label: 'User', role: ROLE_ADMIN }
#            - '@EasyAdmin/form/bootstrap_4.html.twig'
#            - '@VichUploader/Form/fields.html.twig'
        menu:
            - { label: 'User', entity: 'User', role1: ROLE_ADMIN }
            - { label: 'Attendence', entity: 'Attendence', role:[ ROLE_USER, ROLE_ADMIN] }


        brand_color: darkred
        assets:
            css: ['css/custom_backend.css']


    list:
        title: 'List of %%entity_label%%'
        actions: ['show']

    entities:
        Attendence:
            role: ROLE_USER
            class: AppBundle\Entity\Attendence
            label: Attendence
#            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            list:
                fields:
                    - { property: 'id'}
                    - "timein"
                    - "timeout"
                    - "date"
                    - "atten_id"
                    - "status_abs_pre"
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

                # ...
            show:
                fields:
                    - { property: 'id'}
                    - "timein"
                    - "timeout"
                    - "date"
                    - "atten_id"
                    - "status_abs_pre"
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            form:
                fields:
                    - "timein"
                    - "timeout"
                    - "date"
#                    - "atten_id"
#                    - "status_abs_pre"
                    - { property: 'imageFile', type: 'vich_image' }


        User:
            role: ROLE_ADMIN
            class: AppBundle\Entity\User
            label: User
            list:
                fields:
                    - "id"
                    - "username"
                    - "email"
                    - "enabled"
                    - "password"
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            show:
                fields:
                    - "id"
                    - "username"
                    - "email"
                    - "enabled"
                    - "password"
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            form:
                fields:
                    - "username"
#                    - "username_canonical"
                    - "email"
#                    - "email_canonical"
                    - "enabled"
#                    - "salt"
                    - "plainPassword"
#                    - "last_login"
#                    - "confirmation_token"
#                    - "password_requested_at"
                    - "roles"
#                    - "image"
                    - { property: 'imageFile', type: 'vich_image' }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%%"
        sender_name: "%%"
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/web%app.path.product_images%'
