# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# config/routes/easy_admin.yaml
easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/'
    type: annotation
    prefix: /easyadmin
